[Newton's Method] Adding a Lecture on the Application of Newton's Method
QuantEcon/lecture-python.myst pull request #279
Opened 2022-11-09 23:11 UTC by HumphreyYang

2022-11-10 01:23 UTC, mmcky commented on lectures/newton_method.md
> +\begin{align}
@HumphreyYang `align` is a math environment so this is a double math environment in latex output which LaTeX struggles with. So you need to swap these to `\begin{aligned}`

https://manual.quantecon.org/writing/styleguide.html#mathematical-notation

2022-11-10 01:23 UTC, mmcky requested changes
@HumphreyYang I think with that change it should build the `pdf`

2022-11-10 01:30 UTC, HumphreyYang commented
> @HumphreyYang I think with that change it should build the `pdf`

Many thanks @mmcky, I will read through the QuantEcon Operations Manual since I haven't seen it before.

2022-11-10 01:33 UTC, mmcky commented
> > @HumphreyYang I think with that change it should build the `pdf`
> 
> Many thanks @mmcky, I will read through the QuantEcon Operations Manual since I haven't seen it before.

thanks @HumphreyYang any suggestions to improve it are most welcome.

2022-11-11 00:22 UTC, HumphreyYang commented
Hi @mmcky,

This is a first pass for a new lecture on Newton's Method. Here is the [latest deployment](https://636d945b45b2ff54fa83d990--nostalgic-wright-5fa355.netlify.app). Could you please have a look at the lecture and kindly let me know where I should improve?

In addition, there are two specific things I would like to ask for your idea/opinion on:

1. It seems that the drop-down class for the hint admonitions will have a very wide blank space when it includes a formula using `$$` or `{math}` directive. Is there any way to avoid it?
2. Do you think it is a good idea to print out a long output in the solution part for exercise 1 and 2? Or it would be better to separate out each attempt. 

Many thanks in advance.

2022-11-15 00:37 UTC, jstac commented
Hi @mmcky , please let me know when you've had a chance to look at this.

2022-11-15 00:39 UTC, mmcky commented
thanks for the ping @jstac -- I will review this early this afternoon.

2022-11-15 04:19 UTC, mmcky reviewed
@HumphreyYang this is a really interesting lecture. Thanks for your help putting it together.

My main comment is that it may be useful to explain a few of the early steps a bit more. There is one example, where you say: using the formulae (but it isn't immediately obvious where the formulae comes from) -- see individual comments. 

Super neat how you scale this up to a high dimension. 

I will see what's going on with GPU and update from main if needed.

2022-11-15 04:19 UTC, mmcky commented on lectures/newton_method.md
> +The lecture will apply Newton's method in one-dimensional and multi-dimensional settings to solve fixed-point and root-finding problems.
@HumphreyYang is `newton's method` the same as `newton-rhapson` method? If it is it might just be worth adding in a `note` box? In engineering this is usually referred to as newton-rhapson` but might be different in economics. (cc @jstac)

2022-11-15 04:19 UTC, mmcky commented on lectures/newton_method.md
> +:label: newtons_method
- [ ] enable `chtml` rendering as the `svg` rendering with text doesn't look very nice. (@mmcky)

2022-11-15 04:19 UTC, mmcky commented on lectures/newton_method.md
> +params = create_solow_params(α=0.05, δ=0.5)
@HumphreyYang so is the main benefit of using `namedtuple` here that you can vary a sub-set of the values while the other values are retained?

2022-11-15 04:19 UTC, mmcky commented on lectures/newton_method.md
> +Here's a function $q$ such that iterating with $q$ is equivalent to Newton's method.
Where does this function come from. It might be nice to explain a bit more about $q$

2022-11-15 04:19 UTC, mmcky commented on lectures/newton_method.md
> +This is also a more familiar formula for Newton's method.
@HumphreyYang I am not sure what `a more familiar formula` means here. To me this suggests we should use this formulae to begin with. Perhaps you mean using the `Newton method formula directly to iterate`?

2022-11-15 04:19 UTC, mmcky commented on lectures/newton_method.md
> +This naturally leads us to use Newton's method to solve multi-dimensional problems for which we will use the powerful auto-differentiation functionality in `jax` to solve intricate calculations.
Super cool! :-)

2022-11-15 04:19 UTC, mmcky commented
- [ ] @mmcky to enable `GPU` based workflows as this lecture contains `jax`.

2022-11-15 04:48 UTC, mmcky commented
Enabling `gpu` build support for this repo in https://github.com/QuantEcon/lecture-python.myst/pull/280

2022-11-15 04:48 UTC, mmcky commented
@HumphreyYang I have switched the mathjax engine (for html) to use `chtml` rather than `svg` to improve the math quality on this lecture. When the build finishes do you mind checking this lecture (and a couple others to see if the math is rendering well more generally)

2022-11-15 08:15 UTC, mmcky commented
@HumphreyYang on the latest run I am getting the following error

```
Traceback (most recent call last):
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
e(p, A, b, c)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_7555/861686108.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0me[0m[0;34m([0m[0mp[0m[0;34m,[0m [0mA[0m[0;34m,[0m [0mb[0m[0;34m,[0m [0mc[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_7555/3477763202.py[0m in [0;36me[0;34m(p, A, b, c)[0m
[1;32m      1[0m [0;32mdef[0m [0me[0m[0;34m([0m[0mp[0m[0;34m,[0m [0mA[0m[0;34m,[0m [0mb[0m[0;34m,[0m [0mc[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     [0;32mreturn[0m [0mjnp[0m[0;34m.[0m[0mexp[0m[0;34m([0m[0;34m-[0m [0mjnp[0m[0;34m.[0m[0mdot[0m[0;34m([0m[0mA[0m[0;34m,[0m [0mp[0m[0;34m)[0m[0;34m)[0m [0;34m+[0m [0mc[0m [0;34m-[0m [0mb[0m [0;34m*[0m [0mjnp[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0mp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
    [0;31m[... skipping hidden 11 frame][0m

[0;32m/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py[0m in [0;36mdot[0;34m(a, b, precision)[0m
[1;32m   2910[0m     [0;32mreturn[0m [0mlax[0m[0;34m.[0m[0mmul[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2911[0m   [0;32mif[0m [0m_max[0m[0;34m([0m[0ma_ndim[0m[0;34m,[0m [0mb_ndim[0m[0;34m)[0m [0;34m<=[0m [0;36m2[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2912[0;31m     [0;32mreturn[0m [0mlax[0m[0;34m.[0m[0mdot[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mb[0m[0;34m,[0m [0mprecision[0m[0;34m=[0m[0mprecision[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2913[0m [0;34m[0m[0m
[1;32m   2914[0m   [0;32mif[0m [0mb_ndim[0m [0;34m==[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/__w/lecture-python.myst/lecture-python.myst/3/envs/quantecon/lib/python3.9/site-packages/jax/_src/lax/lax.py[0m in [0;36mdot[0;34m(lhs, rhs, precision, preferred_element_type)[0m
[1;32m    730[0m                        preferred_element_type=preferred_element_type)
[1;32m    731[0m   [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 732[0;31m     raise TypeError("Incompatible shapes for dot: got {} and {}.".format(
[0m[1;32m    733[0m         lhs.shape, rhs.shape))
[1;32m    734[0m [0;34m[0m[0m

[0;31mTypeError[0m: Incompatible shapes for dot: got (3, 3) and (5000,).
TypeError: Incompatible shapes for dot: got (3, 3) and (5000,).
```

any ideas?

2022-11-15 22:39 UTC, mmcky commented
@HumphreyYang I have removed `jax` and `jaxlib` in preference for the `pip` install that is paired with the fetching from google of the latest `cuda` dynamic libraries etc. Jax is installed as part of the instance setup.

2022-11-16 21:14 UTC, HumphreyYang commented
Many thanks for the detailed review @mmcky. I will look into this issue and reflect on your comments.

2022-11-17 02:01 UTC, mmcky commented
@HumphreyYang the issue identified by @shlff in https://github.com/QuantEcon/lecture-python.myst/pull/179

seems to be resolved now re: `chtml`

I will rerun that PR. But do let me know if you see any issues re: `chtml` change.

2022-11-17 08:56 UTC, HumphreyYang commented
> My main comment is that it may be useful to explain a few of the early steps a bit more. There is one example, where you say: using the formulae (but it isn't immediately obvious where the formulae comes from) -- see individual comments. 
 

Hi @mmcky ,

Thanks for the comment -- it is right on the point. 

I have added more explanations to fill the gaps. Could you have another look at the latest deployment for any errors/improvements I could fix?

Many thanks.

2022-11-18 00:56 UTC, mmcky commented
thanks @HumphreyYang you have made some really nice changes and updates. Thank you.

2022-11-23 07:19 UTC, jstac commented
Many thanks @HumphreyYang  --- and @mmcky for reviewing.

Is there a deployment I can view?

2022-11-23 07:25 UTC, HumphreyYang commented
> Many thanks @HumphreyYang --- and @mmcky for reviewing.
> 
> Is there a deployment I can view?

Hi @jstac, 

The latest deployment is [here](https://6375e09d94bfde4823821f9c--nostalgic-wright-5fa355.netlify.app). It is hidden under the preview in GitHub action. Many thanks in advance for your review.

2022-11-23 23:58 UTC, mmcky commented
@jstac the `netlify` preview doesn't always post a comment with the latest link. Not entirely sure why. But it is always available in the list of Checks at the bottom of a PR if you scroll down you will see `Netlify Deployment` and clicking on that link will ensure you get the latest preview deployment (as per screenshot)

<img width="840" alt="Screenshot 2022-11-24 at 10 47 21 am" src="https://user-images.githubusercontent.com/8263752/203665580-eb85acdb-ccfd-4543-a9cc-85633f2868b8.png">

2022-11-27 22:30 UTC, jstac commented
Thanks @HumphreyYang .  You've done a very nice job tidying this up and adding exercises.

Please change the title to "Using Newton's method to solve economic models".

After the section title with number 8.2, it would be helpful to have a roadmap of what happens in that section --- set up a model, inspect the fixed point visually, solve by successive approximation, then use Newton's method.  Otherwise the reader will get a bit lost in the details.

Similarly, after the section title with number 8.3, it would be helpful for the reader to have a roadmap of what will be covered in that section.

IMO the lecture still needs more clarification on what Newton's method is and how Newton's method for fixed points differs from that for root finding.    Perhaps I'll take care of that?

Also, we should add the GPU note mentioned in https://github.com/QuantEcon/lecture-python-programming.myst/pull/254

2022-11-27 23:09 UTC, HumphreyYang commented
Thank you so much for the feedback @jstac,

> Please change the title to "Using Newton's method to solve economic models".
> After the section title with number 8.2, it would be helpful to have a roadmap of what happens in that section
> Similarly, after the section title with number 8.3, it would be helpful for the reader to have a roadmap of what will be covered in that section.

They are really good suggestions to improve clarity. I will add these this afternoon. 

> IMO the lecture still needs more clarification on what Newton's method is and how Newton's method for fixed points differs from that for root finding. Perhaps I'll take care of that?

Thanks for the help. I will watch and learn how to write these concepts in a clearer way :)

> Also, we should add the GPU note mentioned in [QuantEcon/lecture-python-programming.myst#254](https://github.com/QuantEcon/lecture-python-programming.myst/pull/254)

Since we are running all lectures using the same setup, I was wondering if it is a good idea to add the spec in the execution statistics page instead of having separate notes in each lecture (CC @mmcky).

2022-11-27 23:09 UTC, HumphreyYang commented
Thank you so much for the feedback @jstac,

> Please change the title to "Using Newton's method to solve economic models".
> After the section title with number 8.2, it would be helpful to have a roadmap of what happens in that section
> Similarly, after the section title with number 8.3, it would be helpful for the reader to have a roadmap of what will be covered in that section.

They are really good suggestions to improve clarity. I will add these this afternoon. 

> IMO the lecture still needs more clarification on what Newton's method is and how Newton's method for fixed points differs from that for root finding. Perhaps I'll take care of that?

Thanks for the help. I will watch and learn how to write these concepts in a clearer way :)

> Also, we should add the GPU note mentioned in [QuantEcon/lecture-python-programming.myst#254](https://github.com/QuantEcon/lecture-python-programming.myst/pull/254)

Since we are running all lectures using the same setup, I was wondering if it is a good idea to add the spec in the execution statistics page instead of having separate notes in each lecture (CC @mmcky).

2022-11-28 02:01 UTC, mmcky commented
> Since we are running all lectures using the same setup, I was wondering if it is a good idea to add the spec in the execution statistics page instead of having separate notes in each lecture (CC @mmcky).

@HumphreyYang I have included the specs of the machine via a link with the details on the `status page`. But I do think a note about the gpu is warranted for each lecture that makes use of a GPU to remind readers of the site that they may need `gpu` support when working locally.

2022-11-28 03:23 UTC, mmcky commented
@jstac @HumphreyYang I have been thinking a bit more about this. I wonder if we can add a `badge` using `sphinx-design` to lectures that make use of a `gpu` in the title. 

https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html

I will open a different PR to try this idea out.

2022-12-02 05:28 UTC, jstac commented
Nice job @HumphreyYang , this is well put together with good attention to detail.  I'll make some small changes ex post but the lecture can go live.  Merging now.

2022-12-02 05:38 UTC, merged