Suggestions for the SVD lecture
QuantEcon/lecture-python.myst pull request #361
Opened 2023-08-16 20:32 UTC by matheusvillasb

Corrected some typos. 

Added a brief description explaining why the Eckart-Young theorem is important.

Added details to how the PCA for any given matrix.

Changed the n_components term in the codes to r_components, so it is in accord with the definition of the Eckward-Young theorem and doesn't create confusion with the n columns of the matrix.

Added an exercise and its solution at the end (I've never used Sphinx, so not sure if it's done correctly).

2023-08-16 23:05 UTC, jstac commented
Many thanks @matheusvillasb for your very helpful corrections and suggestions!

@HumphreyYang , could you please do a first round review of this PR?  @matheusvillasb is a first-time contributor, and hence might need some assistance with QE conventions and myst syntax.

@thomassargent30, just looping you into this discussion since the edits are to your SVD lecture.  @matheusvillasb is a very enthusiastic and hard working masters student based in Europe.

2023-08-16 23:17 UTC, thomassargent30 commented
Dear Humphrey,

Please let me know how I can help.  I wrote most of the SVD lecture and am
responsible for all of the bugs.

Tom

On Wed, Aug 16, 2023 at 5:05 PM John Stachurski ***@***.***>
wrote:

> Many thanks @matheusvillasb
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matheusvillasb&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=jaOvCvFtcxNa9JjxpJqJP6-WE8TPhmuhWpHTYv8yY6M&e=>
> for your very helpful corrections and suggestions!
>
> @HumphreyYang
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_HumphreyYang&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=CbYLKt8p2j6MTcXMJLyQsEUjlQbQ9Ls8BDhcDEuD7n8&e=>
> , could you please do a first round review of this PR? @matheusvillasb
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matheusvillasb&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=jaOvCvFtcxNa9JjxpJqJP6-WE8TPhmuhWpHTYv8yY6M&e=>
> is a first-time contributor, and hence might need some assistance with QE
> conventions and myst syntax.
>
> @thomassargent30
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_thomassargent30&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=_ilPWitKrGNlQEPeeQr1kqZ_7lZP_ZKesblhdF62IyQ&e=>,
> just looping you into this discussion since the edits are to your SVD
> lecture. @matheusvillasb
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matheusvillasb&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=jaOvCvFtcxNa9JjxpJqJP6-WE8TPhmuhWpHTYv8yY6M&e=>
> is a very enthusiastic and hard working masters student based in Europe.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QuantEcon_lecture-2Dpython.myst_pull_361-23issuecomment-2D1681379151&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=m54LA3o6H90U9k2YYVjLmLhV-8DwjrxN9Mik6dppVoI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AA63MTUJ2FOCGV3TFEGGFT3XVVG5LANCNFSM6AAAAAA3TB6O5I&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hV4qLWg4zodvX-YQ-ETIbA&m=EfK6cqaDA36Kw99qAGZfrvvhgu_f0DbrJgxG_W8q1DHqE_QCoA-6_Rd6cdoiyc3E&s=Mu1osRFFGIOZYwY8sra05HVOn2sTl09FBOd5MMZehM4&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-17 06:38 UTC, HumphreyYang requested changes
Great changes @matheusvillasb,

Please kindly check my comments above and feel free to commit them. I will do another round in a separate PR once these changes are made.

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{y \neq 0} \frac{||X y ||}{||y||} = \sigma_1$
```suggestion
* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{||y|| \neq 0} \frac{||X y ||}{||y||} = \sigma_1$
```

Nice catch! I think it is clearer if we say $||y|| \neq 0$ instead of $y \neq 0$.

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p_x p$ matrix through the SVD.
```suggestion
This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p \times p$ matrix through the SVD. 
```

I think you are suggesting $p \times p$ here.

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can order these singular val
This is a great addition, but we often make sentences short in lectures. I propose we shorten it as 

```suggestion
Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can take $r$ leading eigenvalues ordered by magnitude.
```

Please feel free to take or leave this suggestion.

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +This is what model reduction is about, we project the data into a new space, where we extract the patterns that are behind this data, and then we can then keep most of the important patterns and trun
I think the previous sentence is very clear already. Would you suggest leaving this out for simplicity?

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +As we have seen before, the SVD is a way to decompose a matrix into useful components, just like polar decomposition, eigen decomposition and many others. PCA on the other hand, is method that builds
```suggestion
As we have seen before, the SVD is a way to decompose a matrix into useful components, just like polar decomposition, eigendecomposition, and many others. 

PCA, on the other hand, is a method that builds on the SVD to analyze data. The goal is to apply certain steps, to help better visualize patterns in data, using statistical tools to capture the most important patterns in data.
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
>  You can read about the Eckart-Young theorem and some of its uses here <https://en.wikipedia.org/wiki/Low-rank_approximation>.
```suggestion
You can read about the Eckart-Young theorem and some of its uses [here](https://en.wikipedia.org/wiki/Low-rank_approximation).
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
>  Using `full-matrices=False` returns a reduced singular value decomposition.
```suggestion
The cells above illustrate the application of the  `full_matrices=True` and `full_matrices=False` options.
Using `full_matrices=False` returns a reduced singular value decomposition.
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +**Step 1: Standardize the data:** Because our data matrix may hold variables of different units and scales like mentioned above, we first need to standardize the data. First by computing the average
```suggestion
**Step 1: Standardize the data:** 

Because our data matrix may hold variables of different units and scales, we first need to standardize the data. 

First by computing the average of each row of $X$.
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +**Step 2: Compute the covariance matrix:** Then because we want to extract the relationships between variables rather than just their magnitude, in other words, we want to know how they can explain e
```suggestion
**Step 2: Compute the covariance matrix:** 

Then because we want to extract the relationships between variables rather than just their magnitude, in other words, we want to know how they can explain each other, we compute the covariance matrix of $B$.
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +C = \frac{1}{{n}} B^T  B
```suggestion
C = \frac{1}{{n}} B^\top  B
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +If the matrix $C$ is diagonalizable, we can eigendecompose it, find its eigenvalues and rearrange the eigenvalue and eigenvector matrices in a decreasing other. If $C$ is not diagonalizable, we can p
```suggestion
If the matrix $C$ is diagonalizable, we can eigendecompose it, find its eigenvalues and rearrange the eigenvalue and eigenvector matrices in a decreasing other. 

If $C$ is not diagonalizable, we can perform an SVD of $C$:
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +To relate an SVD to a PCA (principal component analysis) of data set $X$, first construct  the  SVD of the data matrix $X$:
```suggestion
To relate an SVD to a PCA of data set $X$, first construct the SVD of the data matrix $X$:
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +
I think this should not be in a code block. 

Please remove

````
```{code-cell} python3
...
```
````

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +**Step 5: Create the Score Matrix:
```suggestion
**Step 5: Create the Score Matrix:**
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +We can now decide how many singular values to pick, based on how much variance you want to retain. (e.g., retaining 95% of the total variance).
```suggestion
We can now decide how many singular values to pick, based on how much variance you want to retain. (e.g., retaining 95% of the total variance). 

We can obtain the percentage by calculating the variance contained in the leading $r$ factors divided by the variance in total:
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +In these cases, the $ (X^T X) $ matrix is not inversible. Its determinant is zero or close to zero and we cannot invert it.
```suggestion
In these cases, the $ (X^\top X) $ matrix is not inversible. Its determinant is zero or close to zero and we cannot invert it.
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +In Ordinary Least Squares (OLS), we learn to compute $ \hat{\beta} = (X^T X)^{-1} X^T y $, but there are cases such as when we have colinearity or an underdetermined system: **short fat** matrix.
```suggestion
In Ordinary Least Squares (OLS), we learn to compute $ \hat{\beta} = (X^\top X)^{-1} X^\top y $, but there are cases such as when we have colinearity or an underdetermined system: **short fat** matrix.
```

2023-08-17 06:38 UTC, HumphreyYang commented on lectures/svd_intro.md
> +What we can do instead is to create what is called a pseudoinverse, a full rank approximation of the inverted matrix so we can compute $ \hat{\beta} $ with it.
```suggestion
What we can do instead is to create what is called a [pseudoinverse](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse), a full rank approximation of the inverted matrix so we can compute $ \hat{\beta} $ with it.
```

2023-08-17 14:34 UTC, matheusvillasb commented on lectures/svd_intro.md
> +* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{y \neq 0} \frac{||X y ||}{||y||} = \sigma_1$
Yes, this is totally right, thank you

2023-08-17 14:34 UTC, matheusvillasb commented on lectures/svd_intro.md
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p_x p$ matrix through the SVD.
I was indeed, sorry and thanks for correcting

2023-08-17 14:42 UTC, matheusvillasb commented on lectures/svd_intro.md
> +Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can order these singular val
Thanks for reducing the phrase, as a latin language speaker, I tend to make texts too prolix. 

But I would keep the words singular values instead of eigenvavalues, while it is true that you can almost use them interchangeably, one being the square of the other when we have invertible matrices.

The theorem applies to any mxn matrix. We could only eigendecompose and find eigenvalues if these matrices were square and diagonalizable which is not the case for any mxn matrix.

2023-08-17 14:42 UTC, matheusvillasb commented on lectures/svd_intro.md
> +This is what model reduction is about, we project the data into a new space, where we extract the patterns that are behind this data, and then we can then keep most of the important patterns and trun
Sure! Thanks

2023-08-17 14:43 UTC, matheusvillasb commented on lectures/svd_intro.md
> +As we have seen before, the SVD is a way to decompose a matrix into useful components, just like polar decomposition, eigen decomposition and many others. PCA on the other hand, is method that builds
Again sorry for being prolix and thanks for the changes.

2023-08-17 14:45 UTC, matheusvillasb commented on lectures/svd_intro.md
> +We can now decide how many singular values to pick, based on how much variance you want to retain. (e.g., retaining 95% of the total variance).
Thanks for making it clearer

2023-08-17 14:51 UTC, matheusvillasb commented on lectures/svd_intro.md
> +What we can do instead is to create what is called a pseudoinverse, a full rank approximation of the inverted matrix so we can compute $ \hat{\beta} $ with it.
Thank you for all the changes, I think they make everything indeed more clear and concise. 谢谢!

2023-08-17 14:57 UTC, matheusvillasb commented on lectures/svd_intro.md
> +If the matrix $C$ is diagonalizable, we can eigendecompose it, find its eigenvalues and rearrange the eigenvalue and eigenvector matrices in a decreasing other. If $C$ is not diagonalizable, we can p
Thanks, it is much better this way

2023-08-17 16:06 UTC, matheusvillasb commented
Thank you so much Humphrey!

Thanks so much for reviewing everything I did and making it more concise! I
committed the changes, there was just the third suggestion where you
suggested me to write "the leading eigenvalues", but in that case
particularly, the theorem works for any matrix not only those that can be
eigendecomposed, so singular values is more appropriate. Other than that, I
think you made everything much better, thanks!

So as I said, I committed the changes and also made a new pull request, I
hope this works.
I'm sorry if I did anything wrong, I'm still figuring out how to do it.

Thank you very much! If you don't mind, I'll start on proofreading the DMD
lectures and proposing exercises and small changes if you don't mind. Or if
you need help with anything else, I'm just really glad to help!!


Matheus



Le jeu. 17 août 2023 à 08:38, Humphrey Yang ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Great changes @matheusvillasb <https://github.com/matheusvillasb>,
>
> Please kindly check my comments above and feel free to commit them. I will
> do another round in a separate PR once these changes are made.
> ------------------------------
>
> In lectures/svd_intro.md
> <https://github.com/QuantEcon/lecture-python.myst/pull/361#discussion_r1296598217>
> :
>
> > @@ -350,7 +350,7 @@ of dimension $m \times n$.
>
>  Three popular **matrix norms**  of an $m \times n$ matrix $X$ can be expressed in terms of the singular values of $X$
>
> -* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{y \in \textbf{R}^n} \frac{||X y ||}{||y||} = \sigma_1$
> +* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{y \neq 0} \frac{||X y ||}{||y||} = \sigma_1$
>
> ⬇️ Suggested change
>
> -* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{y \neq 0} \frac{||X y ||}{||y||} = \sigma_1$
> +* the **spectral** or $l^2$ norm $|| X ||_2 = \max_{||y|| \neq 0} \frac{||X y ||}{||y||} = \sigma_1$
>
> Nice catch! I think it is clearer if we say $||y|| \neq 0$ instead of $y
> \neq 0$.
> ------------------------------
>
> In lectures/svd_intro.md
> <https://github.com/QuantEcon/lecture-python.myst/pull/361#discussion_r1296599805>
> :
>
> > @@ -360,6 +360,13 @@ $$
>  \hat X_r = \sigma_1 U_1 V_1^\top  + \sigma_2 U_2 V_2^\top  + \cdots + \sigma_r U_r V_r^\top
>  $$ (eq:Ekart)
>
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p_x p$ matrix through the SVD.
>
> ⬇️ Suggested change
>
> -This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p_x p$ matrix through the SVD.
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p \times p$ matrix through the SVD.
>
> I think you are suggesting $p \times p$ here.
> ------------------------------
>
> In lectures/svd_intro.md
> <https://github.com/QuantEcon/lecture-python.myst/pull/361#discussion_r1296604833>
> :
>
> > @@ -360,6 +360,13 @@ $$
>  \hat X_r = \sigma_1 U_1 V_1^\top  + \sigma_2 U_2 V_2^\top  + \cdots + \sigma_r U_r V_r^\top
>  $$ (eq:Ekart)
>
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p_x p$ matrix through the SVD.
> +
> +Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can order these singular values in a decreasing order by magnitude and set a threshold $r$, from where past this point we set all singular values to zero.
>
> This is a great addition, but we often make sentences short in lectures. I
> propose we shorten it as
> ⬇️ Suggested change
>
> -Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can order these singular values in a decreasing order by magnitude and set a threshold $r$, from where past this point we set all singular values to zero.
> +Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can take $r$ leading eigenvalues ordered by magnitude.
>
> Please feel free to take or leave this suggestion.
> ------------------------------
>
> In lectures/svd_intro.md
> <https://github.com/QuantEcon/lecture-python.myst/pull/361#discussion_r1296605473>
> :
>
> > @@ -360,6 +360,13 @@ $$
>  \hat X_r = \sigma_1 U_1 V_1^\top  + \sigma_2 U_2 V_2^\top  + \cdots + \sigma_r U_r V_r^\top
>  $$ (eq:Ekart)
>
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p_x p$ matrix through the SVD.
> +
> +Moreover, if some of these $p$ singular values carry more information than others, and if we want to have the most amount of information with the least amount of data, we can order these singular values in a decreasing order by magnitude and set a threshold $r$, from where past this point we set all singular values to zero.
> +
> +This is what model reduction is about, we project the data into a new space, where we extract the patterns that are behind this data, and then we can then keep most of the important patterns and truncate the rest.
>
> I think the previous sentence is very clear already. Would you suggest
> leaving this out for simplicity?
> ------------------------------
>
> In lectures/svd_intro.md
> <https://github.com/QuantEcon/lecture-python.myst/pull/361#discussion_r1296619809>
> :
>
> > @@ -569,19 +576,78 @@ where for $j = 1, \ldots, n$ the column vector $X_j = \begin{bmatrix}X_{1j}\\X_{
>
>  In a **time series** setting, we would think of columns $j$ as indexing different __times__ at which random variables are observed, while rows index different random variables.
>
> -In a **cross section** setting, we would think of columns $j$ as indexing different __individuals__ for  which random variables are observed, while rows index different **attributes**.
> +In a **cross-section** setting, we would think of columns $j$ as indexing different __individuals__ for  which random variables are observed, while rows index different **attributes**.
> +
> +As we have seen before, the SVD is a way to decompose a matrix into useful components, just like polar decomposition, eigen decomposition and many others. PCA on the other hand, is method that builds on the SVD, to analyse data. The goal is to apply certain steps, to help better visualize patterns in data, using statistical tools to capture the most important patterns in data.
>
> ⬇️ Suggested change
>
> -As we have seen before, the SVD is a way to decompose a matrix into useful components, just like polar decomposition, eigen decomposition and many others. PCA on the other hand, is method that builds on the SVD, to analyse data. The goal is to apply certain steps, to help better visualize patterns in data, using statistical tools to capture the most important patterns in data.
> +As we have seen before, the SVD is a way to decompose a matrix into useful components, just like polar decomposition, eigendecomposition, and many others.
> +
> +PCA, on the other hand, is a method that builds on the SVD to analyze data. The goal is to apply certain steps, to help better visualize patterns in data, using statistical tools to capture the most important patterns in data.
>
> ------------------------------
>
> In lectures/svd_intro.md
> <https://github.com/QuantEcon/lecture-python.myst/pull/361#discussion_r1296620604>
> :
>
> > @@ -360,6 +360,13 @@ $$
>  \hat X_r = \sigma_1 U_1 V_1^\top  + \sigma_2 U_2 V_2^\top  + \cdots + \sigma_r U_r V_r^\top
>  $$ (eq:Ekart)
>
> + [...]

2023-08-17 22:54 UTC, HumphreyYang commented
> so singular values is more appropriate. 

Hi Matheus,

You are absolutely right. That was a typo from me. 

Thanks,
Humphrey

2023-08-18 03:29 UTC, jstac commented on lectures/svd_intro.md
> +This is a very powerful theorem, it says that we can take our $ m \times n $ matrix $X$ that in not full rank, and we can best approximate it to a full rank $p \times p$ matrix through the SVD.
Please changes as follows

"...powerful theorem that says..."
"...approximate it by a..."

2023-08-18 03:30 UTC, jstac commented on lectures/svd_intro.md
> +But more about it later when we present Principal Component Analysis.
"We'll say more about this later when..."

2023-08-18 03:32 UTC, jstac commented on lectures/svd_intro.md
> +In these cases, the $ (X^\top X) $ matrix is not inversible. Its determinant is zero or close to zero and we cannot invert it.
"...not invertible (its determinant is zero) or ill-conditioned (its determinant is very close to zero)."

2023-08-18 03:35 UTC, jstac commented
Thanks @matheusvillasb , these are nice changes.  Thoughtful and well written.

I've requested some very minor edits.  Would you mind to make those changes and push them to this PR?

Once you have made those edits to the PR I'll pass the review over to @mmcky and @thomassargent30 so we can get this merged.

(Thanks also to @HumphreyYang for a very useful review.)

2023-08-19 15:42 UTC, matheusvillasb reviewed
Did the changes John asked, sorry for the delay, I thought I had commited it before, but it didn't.

2023-08-20 03:13 UTC, jstac commented
Great, thanks @matheusvillasb .  Over to you @mmcky and @thomassargent30 .

2023-09-01 04:05 UTC, jstac commented
@HumphreyYang , could you please look and see why this is failing?

2023-09-01 04:10 UTC, HumphreyYang commented
Hi @jstac,

I think @mmcky raised this issue of GitHub action. It rejects running PR from a fork as it is reluctant to share the credentials for EC2. I think we have yet to find a good solution other than building it locally (CC @mmcky).

2023-12-12 05:54 UTC, mmcky commented
@HumphreyYang can you run this locally and cross-check the builds and report back. 

It would be great if you can also fix the merge conflict.

2023-12-12 05:55 UTC, mmcky commented
> @HumphreyYang can you run this locally and cross-check the builds and report back.
> 
> It would be great if you can also fix the merge conflict.

Alternatively please transfer the PR to a local branch and push (giving @matheusvillasb the credit to get `CI` to pass)

2023-12-13 23:09 UTC, mmcky commented
Closing this in preference for #375 (migrated to a local branch)

2023-12-14 00:49 UTC, mmcky commented
I have re-opened this as we can use #375 as a test environment so long as we move those changes back to this PR (that can't execute the previews). @HumphreyYang makes a good point in that we want attribution to be retained for @matheusvillasb so it will be better to merge this into `main` than #375. 

@HumphreyYang can you use `gh cli` to 

```
gh checkout pr matheusvillasb:main
<resolve conflict>
git merge main
git push
```

to bring this PR (fork in line with #375)

2023-12-14 00:50 UTC, mmcky commented
@HumphreyYang I see the fix https://github.com/QuantEcon/lecture-python.myst/pull/375/commits/0770ded8d4310c345c31bc67f704b3dea9623f79 and I can apply this if you're busy today. 👍

2023-12-14 01:02 UTC, mmcky commented
@jstac a replica of this is available here: https://github.com/QuantEcon/lecture-python.myst/pull/375

and a preview

https://65782eb0f8c9513bb97425e7--nostalgic-wright-5fa355.netlify.app/svd_intro.html

2023-12-19 22:59 UTC, jstac commented
Hi @mmcky, thanks for organizing.  Thanks @matheusvillasb for putting this together and @HumphreyYang for the review.

I'm happy with these changes but they should be approved by @thomassargent30 before being made live.

2023-12-23 05:08 UTC, mmcky commented
thanks @matheusvillasb for these proposed changes.

Thanks @HumphreyYang @jstac for your comments and reviews. 

@thomassargent30 has reviewed and will make a few minor changes once merged into the main branch.

2023-12-23 05:08 UTC, merged

2024-01-01 23:22 UTC, mmcky commented
thanks once again @matheusvillasb -- these changes are going live today.