REPLICA: PR #355
QuantEcon/lecture-python.myst pull request #382
Opened 2023-12-19 05:02 UTC by mmcky

This is a replicate of #355

2023-12-19 05:20 UTC, shlff requested changes
Thanks @mmcky . Hi @jstac and @oyamad , please find my reviews here.

2023-12-19 05:20 UTC, shlff commented on lectures/lake_model.md
> +        x = np.array([self.A_hat[1, 0], self.A_hat[0, 1]])
```suggestion
        x = np.array([self.A_hat[0, 1], self.A_hat[1, 0]])
```

Please find experiment:

https://gist.github.com/shlff/02f5aac35f8793cdf08935e13174b131

where method with ``x = np.array([self.A_hat[0, 1], self.A_hat[1, 0]])`` generates the same result as the original iterative method.

2023-12-19 05:20 UTC, shlff commented on lectures/lake_model.md
> +        x = np.array([self.A_hat[1, 0], self.A_hat[0, 1]])
```suggestion
        x = np.array([self.A_hat[0, 1], self.A_hat[1, 0]])
```

Same reason here.

2023-12-20 03:23 UTC, mmcky commented
Closing as no longer required

2023-12-20 03:23 UTC, closed without merging